version: "3.8"

services:
  redis_db:
    image: "redis:alpine"
    container_name: redis_db
    command: redis-server
    volumes:
      - ${PWD}/../../../modes/from-source/.state/blockscout/redis-data:/data
