services:

  indexer-db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5433:5432
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'index'
    volumes:
      - ${PWD}/.state/indexer-db/pg_data:/var/lib/postgresql/data

  indexer-db-init:
    build:
      dockerfile: ${PWD}/modules/indexer-db-init/Dockerfile
      context: ${PWD}/modules/indexer-db-init
    depends_on:
      - indexer-db
    networks:
      - internal
    environment:
      POSTGRES_HOST: 'indexer-db'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'index'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  api-db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'api'
    volumes:
      - ${PWD}/.state/api-db/pg_data:/var/lib/postgresql/data

  api-db-init:
    build:
      dockerfile: ${PWD}/modules/api-db-init/Dockerfile
      context: ${PWD}/modules/api-db-init
    depends_on:
      - api-db
    networks:
      - internal
    environment:
      POSTGRES_HOST: 'api-db'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'api'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      INITIAL_USER_SAFE_ADDRESS: '0x3Ac100f2EF20Ab4c6fdf6594Ba633C13e3f06b44'
      INITIAL_USER_SAFE_OWNER_ADDRESS: '0x85a88313b37676ef7F846E00287090E75931E44B'
      INITIAL_ORG_SAFE_ADDRESS: '0x2D76A8369d71FD018540c008EC0b456076985833'
      INITIAL_ORG_SAFE_OWNER_ADDRESS: '0x85a88313b37676ef7F846E00287090E75931E44B '
      INITIAL_USER_NAME: 'root'
      INITIAL_USER_EMAIL: 'root@example.com'
      APP_URL: 'http://localhost:8080'

  api-server:
    image: circlesubi/api-server:dev
    restart: unless-stopped
    depends_on:
      - api-db-init
      - indexer-db-init
      - ganache
      - blockchain-indexer
      - minio
    networks:
      - internal
    ports:
      - 8989:8989
    environment:
      APP_ID: 'api-server-local'
      APP_URL: 'http://localhost:8080/;'
      BLOCKCHAIN_INDEX_DB_CONNECTION_STRING: 'postgresql://readonly_user:postgres@indexer-db:5432/index'
      BLOCKCHAIN_INDEX_WS_URL: 'ws://blockchain-indexer:8675'
      BUCKET_ENDPOINT: 'http://minio:9000'
      BUCKET_KEY: '0womfwnewqmqsclowyds'
      BUCKET_SECRET: 'ffw3jiwienvqncyewosaqwncxaxcf23ncsdnj'
      CONNECTION_STRING_RO: 'postgresql://postgres:postgres@api-db/api'
      CONNECTION_STRING_RW: 'postgresql://postgres:postgres@api-db/api'
      CORS_ORIGINS: 'http://localhost:8080'
      DEBUG: 'true'
      DELAY_START: '0'
      EXTERNAL_DOMAIN: 'localhost'
      INVITATION_FUNDS_SAFE_ADDRESS: '0x0bBE70Ac8D707EA1b65A03c7911BaD9A4b9f277A'
      INVITATION_FUNDS_SAFE_KEY: '0x5bc6328efff9fc724aad89edf1356a6ba7bee56368b4b9b47b1f29a5cd6d73c7'
      OPERATOR_ORGANISATION_ADDRESS: '0x2D76A8369d71FD018540c008EC0b456076985833'
      CIRCLES_HUB_ADDRESS: '0x5528544b97869ce105Be00fcCF250f659e787034'
      MAIL_FROM: 'notifcations@circles.land'
      PATHFINDER_URL: 'http://pathfinder2'
      RPC_GATEWAY_URL: 'http://ganache:8545'
      SMTP_DEBUG: 'true'
      SMTP_HOST: 'smtp.example.com'
      SMTP_PASSWORD: '123'
      SMTP_PORT: '465'
      SMTP_USER: 'mail_sender'

  # Master safe address is: 0x5E484da6227AB3BA047121742ee766CC6389db4f
  # Safe factory address is: 0xD5E7d393226A6e9089601080E4b92BcaF536BaDA
  blockchain-indexer:
    image: ghcr.io/circlesland/blockchain-indexer:0.0.67
    expose:
      - 8675
    depends_on:
      - ganache
      - indexer-db
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 8675:8675
    environment:
      INDEXER_WEBSOCKET_URL: 'http://0.0.0.0:8675'
      INDEXER_RPC_GATEWAY_URL: 'http://ganache:8545'
      HUB_ADDRESS: '0x5528544b97869ce105Be00fcCF250f659e787034'
      INDEXER_CONNECTION_STRING: 'Server=indexer-db;Port=5432;Database=index;User ID=postgres;Password=postgres;Command Timeout=240;'

  ganache:
    build:
      dockerfile: ${PWD}/modules/ganache/Dockerfile
      context: ${PWD}/modules/ganache
    expose:
      - 8545
    networks:
      - internal
    ports:
      - 8545:8545
    volumes:
      - ${PWD}/.state/ganache:/var/ganache-db

  other-blockchain-user:
    restart: unless-stopped
    build:
      dockerfile: ${PWD}/modules/other_chain_user/Dockerfile
      context: ${PWD}/modules/other_chain_user
    depends_on:
      - ganache
    networks:
      - internal
    environment:
      RPC_URL: 'http://ganache:8545'
      TO_ADDRESS: '0x85a88313b37676ef7F846E00287090E75931E44B'
      PRIVATE_KEY: '0x8a49c61f64ed99f8a59a9bd62cd39238f7256beead025b86e25476e329637b93'

  pathfinder2-updater:
    depends_on:
      - pathfinder2
      - blockchain-indexer
    image: circlesubi/pathfinder2-updater:dev
    restart: unless-stopped
    networks:
      - internal
    environment:
      INDEXER_DB_CONNECTION_STRING: 'Server=indexer-db;Port=5432;Database=index;User ID=postgres;Password=postgres;Command Timeout=240;'
      INDEXER_WS_URL: 'ws://blockchain-indexer:8675'
      INTERNAL_CAPACITY_GRAPH_PATH: '/var/pathfinder2/data/capacity_graph.db'
      EXTERNAL_CAPACITY_GRAPH_PATH: '/var/pathfinder2/data/capacity_graph.db'
      PATHFINDER_RPC_URL: 'http://pathfinder2:54389'
    volumes:
      - ${PWD}/.state/pathfinder:/var/pathfinder2/data

  pathfinder2:
    image: circlesubi/pathfinder2:eeee335
    restart: unless-stopped
    networks:
      - internal
    expose:
      - "54389"
    command:
      - "0.0.0.0:54389"
    volumes:
      - ${PWD}/.state/pathfinder:/var/pathfinder2/data

  pathfinder-proxy:
    image: circlesubi/pathfinder-proxy:dev
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - internal
    environment:
      PORT: '80'
      CORS_ORIGINS: 'http://localhost:8080'
      UPSTREAM_SERVICE_ENDPOINTS: 'http://pathfinder2:54389'
      UPSTREAM_HEALTH_ENDPOINTS: 'http://pathfinder2-updater:8794'

  frontend:
    build:
      dockerfile: ${PWD}/modules/frontend/Dockerfile
      context: ${PWD}/modules/frontend
      args:
        API_ENDPOINT: 'http://localhost:8989'
        CIRCLES_SUBGRAPH_ENDPOINT: 'https://api.thegraph.com/subgraphs/name/circlesubi/circles'
        PATHFINDER_ENDPOINT: 'http://localhost:8081'
        CIRCLES_HUB_ADDRESS: '0x5528544b97869ce105Be00fcCF250f659e787034'
        SAFE_PROXY_FACTORY_ADDRESS: '0xD5E7d393226A6e9089601080E4b92BcaF536BaDA'
        SAFE_ADDRESS: '0x5E484da6227AB3BA047121742ee766CC6389db4f'
        RPC_ENDPOINT: 'http://localhost:8545'
        OPENLOGIN_CLIENT_ID: 'BHqazms23gbTZQ2fYvvUaFzv718Ft8Ox1XwSEqVt81jtZJRQRb-N5cnThtZGSjZF9Dtj9MQxkEQTUo47I_wiihE'
        HERE_API_KEY: 'fhiIkoASi1B-z8R7ytKBnfJltOpaUlYBV1kydXyK1sE'
        PLACES_API_KEY: 'AIzaSyDAh2mCO36_qBtbb00QY3IPGKUsunbBj'
    networks:
      - internal
    ports:
      - 8080:80

  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /export/images && /usr/bin/minio server /export'
    environment:
      MINIO_ACCESS_KEY: '0womfwnewqmqsclowyds'
      MINIO_SECRET_KEY: 'ffw3jiwienvqncyewosaqwncxaxcf23ncsdnj'
    ports:
      - "9000:9000"

networks:
  internal:
