call add_business_category('Sembako');
call add_business_category('Food/Beverage');
call add_business_category('Transportation');
call add_business_category('Farm/Garden');
call add_business_category('Household Goods');
call add_business_category('Repair Services');
call add_business_category('Health Services');
call add_business_category('OTHER Retail');
call add_business_category('Salon');
call add_business_category('Tools/Equipment');
call add_business_category('Landlord');
call add_business_category('Education');
call add_business_category('Utilities');
